version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: movie_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: movie_backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/movies
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    command: pnpm run start:dev

volumes:
  pgdata:
